export const CART_ADD_REQUEST = "CART_ADD_REQUEST";
export const CART_ADD = "CART_ADD";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";

export const CART_REMOVE_REQUEST = "CART_REMOVE_REQUEST";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";

export const CART_GET_REQUEST = "CART_GET_REQUEST";
export const CART_GET_SUCCESS = "CART_GET_SUCCESS";
export const CART_GET_FAIL = "CART_GET_FAIL";

export const CART_STATE_RESET = "CART_STATE_RESET";
