export const CART_ADD = "CART_ADD";
export const CART_REMOVE = "CART_REMOVE";
export const CART_REMOVE_ALL = "CART_REMOVE_SUCCESS";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";

export const CART_GET_REQUEST = "CART_GET_REQUEST";
export const CART_GET_SUCCESS = "CART_GET_SUCCESS";
export const CART_GET_FAIL = "CART_GET_FAIL";

export const CART_STATE_RESET = "CART_STATE_RESET";
