export const PRODUCT_GET_ALL_REQUEST = "PRODUCT_GET_ALL_REQUEST";
export const PRODUCT_GET_ALL_SUCCESS = "PRODUCT_GET_ALL_SUCCESS";
export const PRODUCT_GET_ALL_FAIL = "PRODUCT_GET_ALL_FAIL";

export const PRODUCT_GET_ALL_CATEGORY_REQUEST =
  "PRODUCT_GET_ALL_CATEGORY_REQUEST";
export const PRODUCT_GET_ALL_CATEGORY_SUCCESS =
  "PRODUCT_GET_ALL_CATEGORY_SUCCESS";
export const PRODUCT_GET_ALL_CATEGORY_FAIL = "PRODUCT_GET_ALL_CATEGORY_FAIL";

export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST";
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS";
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL";
